// Turns skills/datin/agents/*.agent.md into one TypeScript module the CLI ships, so `datin agent instructions`
// works offline and the markdown stays the single source the skill and the CLI both read. The `.agent.md`
// suffix keeps `claude.agent.md` from being read as a CLAUDE.md on case-insensitive filesystems.
// Usage: bun run agents:embed (CI fails when the committed module is behind the markdown).
import { readdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const source = new URL("../skills/datin/agents/", import.meta.url);
const target = new URL("../packages/cli/src/agents/instructions.gen.ts", import.meta.url);

const SUFFIX = ".agent.md";
const names = (await readdir(source)).filter((name) => name.endsWith(SUFFIX)).sort();
const entries = await Promise.all(
  names.map(async (name) => {
    const markdown = await Bun.file(new URL(name, source)).text();
    const title = markdown.match(/^# (.+)$/m)?.[1];
    if (!title) throw new Error(`${name} has to start with a "# Title" heading`);
    return { id: name.slice(0, -SUFFIX.length), title, markdown };
  }),
);

const lines = [
  "// Generated by scripts/embed-agents.ts from skills/datin/agents/*.agent.md; edit the markdown, then `bun run agents:embed`.",
  "",
  `export const AGENT_IDS = [${entries.map((entry) => JSON.stringify(entry.id)).join(", ")}] as const;`,
  "",
  "export type AgentId = (typeof AGENT_IDS)[number];",
  "",
  "export interface AgentInstructions {",
  "  readonly title: string;",
  "  readonly markdown: string;",
  "}",
  "",
  "export const AGENT_INSTRUCTIONS: Readonly<Record<AgentId, AgentInstructions>> = {",
  ...entries.map(
    (entry) =>
      `  ${JSON.stringify(entry.id)}: { title: ${JSON.stringify(entry.title)}, markdown: ${JSON.stringify(entry.markdown)} },`,
  ),
  "};",
  "",
];
await Bun.write(target, lines.join("\n"));
// Formatted like every other file, so `generate:check` compares like with like.
await Bun.$`bunx biome format --write ${fileURLToPath(target)}`.quiet();
console.log(`embedded ${entries.length} agents into ${fileURLToPath(target)}`);
